name: sound_cloud_clone
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_gradient_animation_text: ^1.0.2
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  gap: ^3.0.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  assets:
    - assets/icons/
    - assets/animation/
  uses-material-design: true
