name: sound_cloud_clone
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  dropdown_button2: ^2.3.9
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bounce: ^1.1.0
  flutter_gradient_animation_text: ^1.0.2
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  loading_animation_widget: ^1.2.1
  shared_preferences: ^2.3.2
  toastification: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_lint: ^2.3.10

flutter:
  assets:
    - assets/icons/
    - assets/animation/
  uses-material-design: true
